# Generated by Django 4.2.4 on 2023-08-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapi', '0002_meeting_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='club',
            field=models.CharField(default='MIC', max_length=100),
        ),
    ]
