# Generated by Django 4.2.4 on 2023-08-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='club',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
